#Corre o build e os containers
php:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./html:/var/www/html

#Cria uma base de dados e adiciona a password de root  
db:
  image: mysql:5.7
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=savage
    - MYSQL_DATABASE=curso
